---
title: "R Notebook"
output:
  word_document: default
  html_document: default
  pdf_document: default
---



```{r setting}

library(tidyverse)
library(data.table)
library(ggmap)
library(dplyr)

```

```{r Data Importing}
# 2021데이터 불러오기
shop21 <- fread("202109.csv",encoding="UTF-8")
shop21$year <- "2021"
dim(shop21)
# 2020데이터 불러오기
shop20 <- fread("202009.csv",encoding="UTF-8")
shop20$year <- "2020"
dim(shop20)

shop <- do.call("rbind",list(shop21,shop20))
str(shop)
```

```{r Data Cleaning}
colnames(shop)

#필요한 컬럼으로만 정리
shop <- shop %>% rename(업종대분류 = 상권업종대분류명, 업종중분류 = 상권업종중분류명,업종소분류 = 상권업종소분류명)

```
```{r}
library(naniar)
naniar::gg_miss_var(shop,show_pct = TRUE)
```
```{r 연도별 상가변화}
library(ggplot2)
shop %>% group_by(year) %>% summarise(amount = n(),groups ='drop') %>% 
  ggplot(aes(x=year, y=amount, group=1)) + geom_line(color = "tomato",size =2)

```
```{r}
shop %>% group_by(시군구명, year) %>% summarise(amount=n(),groups="drop") %>%
   ggplot(aes(x= 시군구명, y=amount, fill=year)) + geom_bar(stat = "identity",position ='dodge')+
  theme(axis.text.x = element_text(angle = 90))
```
```{r 업종 상가변화}
shop %>% group_by(업종대분류, year) %>% summarise(amount=n(),groups="drop") %>%
   ggplot(aes(x= 업종대분류, y=amount, fill=year)) + geom_bar(stat = "identity",position ='dodge')+
  theme(axis.text.x = element_text(angle = 90))
```
```{r}
library(dplyr)
shop %>% group_by(법정동명, year) %>% summarise(amount=n(),groups="drop") %>% spread(key ='year',value='amount',fill=0) %>% mutate(diff = (`2020`-`2021`)/`2020`*100) %>% arrange(desc(diff)) %>% filter(`2020` >= 1000) %>% tail(10) %>% ggplot(aes(x=reorder(법정동명,-diff),y=diff)) + geom_bar(stat = "identity",fill ='tomato')+
  theme_classic()+labs(title = "법정동별 상가감소율",x="법정동",y="감소비율") + theme(axis.title.x = element_text(angle=90))
```
```{r}
shop_hoegi <- shop %>% filter(법정동명 == "회기동")
shop_hoegi %>% group_by(업종대분류, year) %>% summarise(amount=n(),groups="drop") %>% ggplot(aes(x= 업종대분류, y=amount, fill=year)) + geom_bar(stat = "identity",position ='dodge')+
  theme_classic() + theme(axis.title.x = element_text(angle=90))

shop_hoegi %>% group_by(업종대분류, year) %>% summarise(amount=n(),groups="drop") %>% spread(key ='year',value='amount',fill=0) %>% mutate(diff = (`2020`-`2021`)/`2020`*100) %>% arrange(desc(diff))
```
```{r}
register_google(key=myapi)
map <- get_map(location = "호랑이양식", zoom = 16, maptype="roadmap", color ="bw")
               
          
ggmap(map) + geom_point(data = shop_hoegi %>% filter(year =='2020'), aes(x=경도, y=위도, color=업종대분류),alpha=0.5,size=2) + labs(title = "2020",x="경도",y="위도")
ggmap(map) + geom_point(data = shop_hoegi %>% filter(year =='2021'), aes(x=경도, y=위도, color=업종대분류),alpha=0.5,size=2) + labs(title = "2021",x="경도",y="위도")
```
```{r}
population <- fread("2109popul.csv",encoding="UTF-8")
population <- population[, c('행정구역', '2021년09월_계_총인구수')]
population <- population %>% rename(시군구명 = 행정구역)
populshop <- left_join (shop21,population,by="시군구명")

```
```{r}
popultable <- populshop %>% group_by(시군구명) %>% summarise(n=n())
populshop <- left_join (popultable,population,by="시군구명")
cntpopulshop <- populshop %>% rename(population = '2021년09월_계_총인구수')

cntpopulshop %>% mutate(count = population/n)  %>% ggplot(aes(x=reorder(시군구명,-count),y=count)) + geom_bar(stat = "identity",fill ='tomato')+
  theme_classic()+labs(title = "서울시 인구당 점포 수",x="시군구명",y="인당 점포 수") + theme(axis.title.x = element_text(angle=90))


```

```{r}
local2021 <- fread("local2021.csv",encoding="UTF-8")
code <- fread("code.csv",encoding="UTF-8")

# 전체 유동인구수
local_plus <-  left_join (local2021,code,by="code")
local0<- local_plus %>% filter(ID == 20210905)
total_local0 <- local0 %>% group_by(code) %>% summarise(total_local= sum(total)/24) %>% arrange(desc(total_local))
to_local0  <-  left_join (total_local0,code,by="code")
to_local0  <- to_local0[,-c(1)]
to_local0  %>% ggplot(aes(x=reorder(서울특별시,-total_local),y=total_local)) + geom_bar(stat = "identity",fill ='tomato')+
  theme_classic()+labs(title = "전체 생활인구수(평균)",x="행정구역",y="mz생활인구수") + theme(axis.title.x = element_text(angle=90))

# MZ세대 유동인구수
mztotal <- local0 %>% group_by(code) %>% summarise(total_local= sum(mztotal)/24) %>% arrange(desc(total_local))
tomz_local0  <-  left_join (mztotal,code,by="code")
tomz_local0  <- tomz_local0 [,-c(1)]
tomz_local0 %>% ggplot(aes(x=reorder(서울특별시,-total_local),y=total_local)) + geom_bar(stat = "identity",fill ='tomato')+
  theme_classic()+labs(title = "MZ세대 생활인구수(평균)",x="행정구역",y="mz생활인구수") + theme(axis.title.x = element_text(angle=90))

# 가장 MZ세대가 유동인구수가 많은 시간대(주)
local_plus <-  left_join (local2021,code,by="code")
local0<- local_plus %>% filter(ID == 20210905 & time == 9 | ID ==20210905 & time == 10 | ID ==20210905 &time == 11 | ID ==20210905 &time == 12 | ID ==20210905 & time == 13 | ID ==20210905 & time == 14 | ID ==20210905 & time == 15 | ID ==20210905 & time == 16 | ID ==20210905 & time == 17 | ID ==20210905 & time == 18)
total_local0 <- local0 %>% group_by(code) %>% summarise(total_local= sum(mztotal)/24) %>% arrange(desc(total_local))
to_local0  <-  left_join (total_local0,code,by="code")
to_local0  <- to_local0[,-c(1)]
to_local0 %>% ggplot(aes(x=reorder(서울특별시,-total_local),y=total_local)) + geom_bar(stat = "identity",fill ='tomato')+
  theme_classic()+labs(title = "MZ세대 생활인구수(주간)",x="행정구역",y="mz생활인구수") + theme(axis.title.x = element_text(angle=90))


# 가장 MZ세대가 유동인구수가 많은 시간대(야)
local_plus <-  left_join (local2021,code,by="code")
local0<- local_plus %>% filter(ID == 20210905 & time == 19 | ID ==20210905 & time == 20 | ID ==20210905 &time == 21 | ID ==20210905 &time == 22 | ID ==20210905 & time == 23 | ID ==20210905 & time == 24 | ID ==20210905 & time == 0 | ID ==20210905 & time == 1 | ID ==20210905 & time == 2 | ID ==20210905 & time == 3 | ID ==20210905 & time == 4 | ID ==20210905 & time == 5 | ID ==20210905 & time == 6 | ID ==20210905 & time == 7 | ID ==20210905 & time == 8)
total_local0 <- local0 %>% group_by(code) %>% summarise(total_local= sum(mztotal)/24) %>% arrange(desc(total_local))
to_local0  <-  left_join (total_local0,code,by="code")
to_local0  <- to_local0[,-c(1)]
to_local0   %>% ggplot(aes(x=reorder(서울특별시,-total_local),y=total_local)) + geom_bar(stat = "identity",fill ='tomato')+
  theme_classic()+labs(title = "MZ세대 생활인구수(야간)",x="행정구역",y="mz생활인구수") + theme(axis.title.x = element_text(angle=90))


```

